# Solver Selection #
optimization:
  # type: human_aware
  # type: base
  type: human_aware_easier
  # type: human_aware_complete
  # type: human_aware_easier
  # type: human_aware_approx
  # type: human_aware_approx_band
  # type: test


  # behaviour: continous
  # objective: makespan
  n_recipe: 10

execution:
  repetitions: 30
  n_recipe: 1

# Problem Info #
# agents_name:
#   - ur5_on_guide
#   - human_right_arm
#
# main_agent: human_right_arm
